### PR TITLE
Add mockup data for developers

### PR DESCRIPTION
**Pull request by abdejohan**

### CODE REVIEW

**Review by Zack-Dx — COMMENTED** [review]
I see as you have added the data the images are not working, they can't be dummy as because we don't serve dummy images you need to have them too.

**Comment by abdejohan** [comment]
All image URLs should now be working and also be of something related to the mockup object they belong to.

**Comment by Zack-Dx** [comment]
> All image URLs should now be working and also be of something related to the mockup object they belong to.

Dev one is good, the restro one is having issues as per the schema. I'd suggest keep this commit upto the devs and make a new pr if you want for the restros thanks.

**Review by Zack-Dx — APPROVED** [review]

**Comment by Zack-Dx** [comment]
> Cool! I removed the other mockups in the PR and and just kept the dev one. My guess about the other mockups is that the "menu" array on restaurants should consists of acutal names of dishes from the menu mockup, Is that correct? Let me know what the issue is and i'll create a new PR for that. 👍🏽


Ya ya you are right regarding the menu ones actually u can check for the images that are used in the api just hit the route as because it's having dishes and actually food like stuff I'd suggest once hit those routes and check if you find such images then open a pr. Thanks for the contribution.

**Pull request merged**
