### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by zainbinfurqan**
Update readme.md

### CODE REVIEW

**Review by Zack-Dx — CHANGES_REQUESTED** [review]
everything is fine I'd love if you can just paraphrase this

**Comment by zainbinfurqan** [comment]
> everything is fine I'd love if you can just paraphrase this

done.

**Review by Zack-Dx — APPROVED** [review]

**Comment by Zack-Dx** [comment]
@zainbinfurqan Ty for the contribution, drop a star on the repo. Spread love!

**Comment by Zack-Dx** [comment]
> Screenshot 2023-10-10 at 11 12 57 PM @Zack-Dx can you please check this

both the labels are attached, you can wait it to update it takes 10-12 hrs.

**Pull request merged**
